### ISSUE TITLE
System.IO.FileNotFoundException  System.Runtime, Version=7.0.0.0

### ISSUE THREAD

**Issue by mjosborne1** [lizzard77/svelte-dotnet-app-vite#1]
Hello and thanks for the repo for vite/svelte/dotnet
Target Framework in the svelte-dotnet-app-vite.csproj is set to 6.0
I had to set mine to 7.0 to get it to run without errors.

Perhaps you need to indicate in the README which dotnet version you are targetting?

`
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>svelte_dotnet_app_vite</RootNamespace>
  </PropertyGroup>
`

**Comment by lizzard77** [comment]
Thanks for your observation! I'll add a passage to the README.

In addition to switching the target framework moniker to net7.0, the alternative would be including a global.json for .NET 6 (which is what I prefer as .NET 6 is the LTS version). I'll add instructions for that, too.

**Comment by mjosborne1** [comment]
Awesome thanks for that.
Love the template by the way, I think it will be very useful.

**Comment by lizzard77** [comment]
README is updated, and global.json is included
